### ISSUE TITLE
Lispy movement commands that treat atoms and parenthesized s-expressions the same?

### ISSUE THREAD

**Issue by bpstahlman** [abo-abo/lispy#307] opened 2016-09-28 18:09 UTC
`lispy-flow` _almost_ does what I want. The problem is, though it descends into a parenthesized sexp, it does so only if that parenthesized sexp contains another parenthesized sexp. The fact that it skips over atoms is problematic: there are times when I want to go to the next sexp, regardless of whether it's parenthesized or a simple atom. `lispy-forward` doesn't do what I want because it won't descend into an s-expression. What I really need is something analogous to hitting Space in an info manual: i.e., keep going to the next node, even when that means descending a level. Perhaps I've just overlooked it, but I haven't seen anything like that in lispy. `lispy-down` isn't quite right because it skips over atoms.

`forward-sexp` is closer to what I want, I guess, as it won't skip atoms, but it doesn't descend into parenthesized sexp's. I guess I could live with this, since I can descend with lispy-flow, then use forward-sexp to move across the list, but forward-sexp isn't even provided by lispy. Is it consistent with "the lispy way" to rely upon it when using lispy?

On the subject of "the lispy way"... I see that `lispy-ace-symbol` can be used to mark (and position cursor on) a specific symbol within the list at point, and then j/k can be used to move the mark to different sexp's (including atoms) in the list. So perhaps I could get some of the functionality I need this way, though it seems a bit heavy-handed. I mean, if I'm planning to move a sexp around within the list, it makes sense, but if I just want to move cursor to an atom within a list (e.g., to modify a symbol, or perhaps to insert a new sexp just before or after it), I'll need to cancel the region mark, and perhaps reposition cursor to the other end of the atom before doing my editing. Also, there's the side-effect of changing the region, when all I wanted was to move the cursor. (Perhaps that's not really an issue. It may be only because I'm relatively new to emacs, but that sort of side-effect seemed problematic to me, if only from an aesthetic standpoint...)

So what's "the lispy way" to move cursor from outside a list to a specific element (possibly an atom) within the list for editing?

Thanks, Brett Stahlman

**Comment by abo-abo** [comment] 2016-09-28 19:05
If you give a code example with the start and desired position, I can be more precise.

But what I usually use is e.g. <kbd>mij</kbd> if <kbd>f</kbd> is no longer applicable.
Example:

```elisp
(equal
 (lispy-with "|(expand-file-name x emacs-git)"
             "mij")
 "(expand-file-name ~x| emacs-git)")
;; => t
```

For `lispy-with` macro, the first arg is the buffer contents, with `|` being the point position, and `~` being the mark position. The second arg is the key sequence and the result is the final buffer state.

**Comment by bpstahlman** [comment] 2016-09-29 01:30
Ah. I hadn't noticed the `lispy-mark-car` mapping for `i`. So I guess there's no real harm in using marks and regions to navigate to the atom I want to edit? I simply hit `m` to deactivate when I'm ready to edit? Incidentally, is `C-M-f` `(forward-sexp)`part of a typical lispy workflow? I notice it's defined in lisp.el. Is that something I can count on always being loaded? What causes it to be loaded?

Incidentally, `lispy-with` looks handy, but it doesn't appear to be defined for me. Is it part of a special development package or something?

Incidentally, as an evil user, I'd been planning to use evil-lisp-state for lisp editing, but now that I've seen the power of lispy's region functionality, I don't want to do without it. I just need to decide whether to use lispy or evil-lispy...

**Comment by abo-abo** [comment] 2016-09-29 07:40
> Ah. I hadn't noticed the lispy-mark-car mapping for i. So I guess there's no real harm in using marks and regions to navigate to the atom I want to edit? I simply hit m to deactivate when I'm ready to edit? 

Yes. I usually just hit <kbd>DEL</kbd> on the marked symbol to delete it and insert something else.  Emacs has great completion for Elisp symbols, deleting and entering a new thing is often faster than editing the old thing char-by-char.

Additionally, for symbol or sexp replacement a nice trick is to press <kbd>n</kbd> to a symbol or sexp to yank it, navigate to a symbol/sexp that you want to replace, mark that with a region and press <kbd>P</kbd>.

> Incidentally, is C-M-f (forward-sexp)part of a typical lispy workflow? I notice it's defined in lisp.el. Is that something I can count on always being loaded? What causes it to be loaded?

It's always loaded, but I rarely use it.

> Incidentally, lispy-with looks handy, but it doesn't appear to be defined for me. Is it part of a special development package or something?

`lispy-with` is defined in `lispy-test.el` in this repository. It's used for defining all of lispy's tests. So if you want to explore a command's intended behavior, look there. It's also great for requesting features or describing bugs, since you're just giving me a new (failing) regression test that I can fix later.

> Incidentally, as an evil user, I'd been planning to use evil-lisp-state for lisp editing, but now that I've seen the power of lispy's region functionality, I don't want to do without it. I just need to decide whether to use lispy or evil-lispy...

Great. There's also `lispyville`, check it out before you decide.

I'm closing this issue, since it appear there's nothing to do. Feel free to open more issues if you find a bug or have an idea for a nice command.

**Closed by abo-abo** 2016-09-29 07:40 UTC

**Comment by bpstahlman** [comment] 2016-09-29 12:02
On Sep 29, 2016 2:40 AM, "Oleh Krehel" <notifications@github.com> wrote:
>>
>> Ah. I hadn't noticed the lispy-mark-car mapping for i. So I guess
there's no real harm in using marks and regions to navigate to the atom I
want to edit? I simply hit m to deactivate when I'm ready to edit?
>
> Yes. I usually just hit DEL on the marked symbol to delete it and insert
something else. Emacs has great completion for Elisp symbols, deleting and
entering a new thing is often faster than editing the old thing
char-by-char.
>
> Additionally, for symbol or sexp replacement a nice trick is to press n
to a symbol or sexp to yank it, navigate to a symbol/sexp that you want to
replace, mark that with a region and press P.
>>
>> Incidentally, is C-M-f (forward-sexp)part of a typical lispy workflow? I
notice it's defined in lisp.el. Is that something I can count on always
being loaded? What causes it to be loaded?
>
> It's always loaded, but I rarely use it.
>>
>> Incidentally, lispy-with looks handy, but it doesn't appear to be
defined for me. Is it part of a special development package or something?
>
> lispy-with is defined in lispy-test.el in this repository. It's used for
defining all of lispy's tests. So if you want to explore a command's
intended behavior, look there. It's also great for requesting features or
describing bugs, since you're just giving me a new (failing) regression
test that I can fix later.
>>
>> Incidentally, as an evil user, I'd been planning to use evil-lisp-state
for lisp editing, but now that I've seen the power of lispy's region
functionality, I don't want to do without it. I just need to decide whether
to use lispy or evil-lispy...
>
> Great. There's also lispyville, check it out before you decide.
>
> I'm closing this issue, since it appear there's nothing to do. Feel free
to open more issues if you find a bug or have an idea for a nice command.

You've been very helpful! That clears it all up for me.

Thanks!
Brett S.
