### ISSUE TITLE
Clojure: When evaluating a namespace form lispy behaves differently from cider(Eval error: nil)

### ISSUE THREAD

**Issue by eipplusone** [abo-abo/lispy#374] opened 2017-09-24 02:35 UTC
Evaluating a `ns` form in lispy by pressing `e(lispy-eval)` returns`Eval error: nil`.

Evaluating the same form by `C-x C-e(cider-eval-last-sexp)` outputs no errors.

It seems the issue is that lispy uses a function other than `cider-interactive-eval` which is where the `ns`special handling is implemented I believe.

**Comment by abo-abo** [comment] 2017-09-27 09:21
Thanks, I'll look into this when I get some time.

**Comment by eipplusone** [comment] 2017-09-27 09:39
I actually have messed around to the point where it is satisfactory for me. Let me do a PR, maybe there's something worthwhile.

**Comment by sooheon** [comment] 2017-12-28 01:46
@eipplusone, what's the word on the PR? I think this issue is causing even non-ns clojure forms to simply not be evaluated, unless the ns form is eval'd with `e` first.

**Comment by abo-abo** [comment] 2017-12-28 09:37
> The ns form needs to be reevaluated with lispy every time you switch to a different ns.

@sooheon I've been getting into Clojure a lot more the last two months. I've added the new ns handling you mention in that period and I like it a lot so far - it allows you to decouple the code from files while you experiment. For example, this notebook will work fine, no matter which namespace CIDER REPL currently has. You can use <kbd>xC</kbd> to clean up the notebook, and <kbd>e</kbd> on the top-level outline to evaluate it:

```elisp
;;* Example

;;** :
(ns user)

;;** :
(def names (ref []))

(defn add-name [name]
  (dosync
   (alter names conj name)))

(add-name "zack")
;; => ["zack"]

;;** :
(add-name "shelley")
;; => ["zack" "shelley"]

;;** :
names
;; => #ref[{:status :ready, :val ["zack" "shelley"]} 0x133dc556]

;;** :
@names
;; => ["zack" "shelley"]

;;** :
(deref names)
;; => ["zack" "shelley"]
```

One more thing that I use:

```elisp
(define-key clojure-mode-map (kbd "C-c C-l") 'cider-load-file)
```

This will reload the whole file, without touching either lispy's or CIDER's current ns.

**Comment by sooheon** [comment] 2017-12-29 05:22
The notebook-like functionality does look nice, but it does not need to be coupled with explicit namespace handling. 

As you mentioned, `cider-load-file` will load the file without touching the ns. In fact, all of the CIDER eval variations do this. So I can jump around files and namespaces, eval whatever code I wish, and CIDER correctly deduces the right ns to eval it in and does it automatically. This follows the principle of not asking the user for information that the system can infer, and it makes exploratory programming much more reproducible. Tying the evaluation context of forms to the file they live in is a good thing for when you revisit your code. Tying it to whatever ns form you happened to press `e` over last is bad imo, because *where* you put your code starts to lose meaning. 

Also, your notebook example is perfectly doable with CIDER style eval, as long as you don't want multiple ns in one file (which is discouraged anyways: https://github.com/bbatsov/clojure-style-guide#one-file-per-namespace).

**Comment by abo-abo** [comment] 2017-12-29 09:47
> where you put your code starts to lose meaning

That's what I'm going for, what I like - exploratory programming.

> (which is discouraged anyways: https://github.com/bbatsov/clojure-style-guide#one-file-per-namespace).

I don't agree with this. What's the point of having a rich namespace API if all we do with it is reduce it to Python-style imports?

In this case, Python-style imports are actually better, since they use a simple construct to handle a simple task. Whereas Clojure uses an elaborate construct to handle a simple task.

> What I propose would be better for lispy is to allow lispy-eval to tie into CIDER better. Always know what CIDER knows (in terms of eval'd values), and be smart about inferring context.

This is already the case. The difference is that you have the option to set `*ns*` manually and keep track of it in a reliable way, instead of relying on `clojure-mode`'s regexes to infer the namespace.  Inferring is nice, except when the wrong thing is inferred and there's no way to at least do a manual override.

**Comment by sooheon** [comment] 2017-12-29 10:36
>> What I propose would be better for lispy is to allow lispy-eval to tie into CIDER better. Always know what CIDER knows (in terms of eval'd values), and be smart about inferring context.

> This is already the case.

I don't believe so. For example, I've just added one spurious ns form to your example:

```
;;** :
(ns user)
(ns banana)
;; => user

;;** :
(def names (ref []))

(defn add-name [name]
  (dosync
   (alter names conj name)))

(add-name "zack")
```

CIDER is smarter about eval'ing any of those forms, it knows to put them in the banana namespace. Even if I specifically eval `(ns user)` and go immediately to `(def names (ref []))`, the result will be `#'banana/names`. This is almost certainly what you want, because if you simply run this code on a clean process, that is what you'll get. 

Say I'm working in two files, `api.clj` and `main.clj`. I want the defs I put in `main.clj` to go in the main ns, and vice versa--CIDER does this, lispy does not. It will happily put all your vars from your entire codebase into one ns, whichever one you initially eval'ed with lispy. This means as I move around my codebase, every evaluation needs to be preceded by moving to the desired ns form and eval'ing that. Why should this not be inferred? Even if you want multiple ns in one file, you would still structure the forms so that the right declarations come after the right ns calls, no? In this case, CIDER will infer the correct ns every time. 

To me, it is less surprising for the editor to respect the code as I've written it into the file, over what I've eval'd last. This means you are more likely to get the same result when you restart the REPL.

**Comment by abo-abo** [comment] 2017-12-29 10:54
> I don't believe so. For example, I've just added one spurious ns form to your example:

Lispy's namespace handling is currently limited to `ns` and `in-ns` forms, and /only/ on their own.

This should work consistently in any file:

```clojure
;;* Example

;;** :
(ns user)
;; => user

;;** :
(ns banana)
;; => banana

;;** :
(def x 1)
;; => #'banana/x
```

**Closed** 2017-12-31 14:34 UTC

**Comment by abo-abo** [comment] 2017-12-31 14:36
@sooheon Thanks for the discussion. I've added automatic namespace detection to `lispy-eval-clojure` (called by <kbd>e</kbd>). Let me know if it works fine.

**Comment by sooheon** [comment] 2018-01-03 04:16
Thanks @abo-abo, the ns detection works. I do have different questions/reports about eval'ing, which I'll put in another issue.

**Comment by eipplusone** [comment] 2018-01-04 19:45
Apologies - my solution was to just `lispy-define-key` the `cider-eval-last-sexp` function. Which is not PR worthy since the way I understand it is not a solid solution since cider prefers evals to be done by `cider-interactive-eval `function, in case it is done by a library.
