### ISSUE TITLE
Unmatched brackets in string

### ISSUE THREAD

**Issue by Somelauw** [abo-abo/lispy#342] opened 2017-03-28 21:37 UTC
I have the following text in a buffer in which lispy is enabled:

```
"g]"
```

If the pointer is after "]", using the function lispy-delete-backwards-or-splice-or-slurp leaves the following:

```
"
```

but I would expect to get:

```
"g"
```

**Comment by abo-abo** [comment] 2017-03-28 21:45
Can't reproduce. I still get "g". Which major-mode / Emacs / settings?

**Comment by Somelauw** [comment] 2017-03-28 22:28
My apologies, the string should be "g}". If the string is "g]", it doesn't give me any problems.
I use these lines for testing:

```
  (define-key evil-normal-state-map (kbd "g]") 'evil-cp-next-closing) ; succeeds
  (define-key evil-normal-state-map (kbd "g}") 'evil-cp-previous-closing) ; fails
```

My lispy configuration is as follows:

```
  (eval-after-load "lispy"
    `(progn
       (lispy-set-key-theme '(special paredit c-digits))
       (define-key lispy-mode-map (kbd "DEL") 'lispy-delete-backward-or-splice-or-slurp)
       (define-key lispy-mode-map (kbd "M-m") 'evil-lispy-mark-symbol) ; enters insert mode first
       (define-key lispy-mode-map (kbd "C-,") 'lispy-kill-at-point)
       (define-key lispy-mode-map (kbd "M-i") 'lispy-iedit)))

  (add-hook 'emacs-lisp-mode-hook (lambda () (lispy-mode 1)))
  (add-hook 'clojure-mode-hook (lambda () (lispy-mode 1)))
  (add-hook 'lisp-mode-hook (lambda () (lispy-mode 1)))
  (add-hook 'scheme-mode-hook (lambda () (lispy-mode 1)))
  ;; (add-hook 'python-mode-hook (lambda () (lispy-mode 1)))
```

With this setup, I can reproduce the problem by pressing DEL.

**Comment by abo-abo** [comment] 2017-03-29 06:29
Still can't reproduce in `*scratch*`. Which `major-mode`?

**Comment by Somelauw** [comment] 2017-04-02 20:46
@abo-abo It happens to me in emacs-lisp when using lispy-delete-backward-or-splice-or-slurp.

Here are three cases where | is the position of point:

```emacs-lisp
   (kbd "M-]|")                          ; ok
   (kbd "M-}|")                          ; this leaves (kbd "|")
   (kbd "g[|")                           ; ok
   (kbd "g]|")                           ; ok
   (kbd "g{|")                           ; ok
   (kbd "g}|")                           ; this leaves (kbd |")
```

**Comment by abo-abo** [comment] 2017-04-03 07:17
I don't see the bug on my system. Can you reproduce with `emacs -Q`?

**Comment by Somelauw** [comment] 2017-04-03 09:10
It turned out that it wasn't lispy's fault, because when I disabled lispy, it was still deleting too much.
The reason I blamed lispy, is that "C-h k DEL" shows lispy-delete-backward-or-splice-or-slurp, so I thought their function would be called.
However, the problem didn't stop until I also disabled smartparens-mode.

**Comment by abo-abo** [comment] 2017-04-03 14:01
OK then. Closing the issue.

**Closed by abo-abo** 2017-04-03 14:01 UTC
